### ISSUE TITLE
how to make child page as laravel return 404

### ISSUE THREAD

**Issue by keung7251** [bigcommerce/laravel-react-sample-app#10]
how to make child page as laravel return 404 when I link localhost/package/123

`

<BrowserRouter>
    <div>
        <Header />

        <Switch>
            <Route exact path="/list" component={ ListOfThings } />
            <Route exact path="/" component={ Home } />
            <Route path="/packgae" component={ Package } />
            <Route path="/packgae/:package" component={ PackageDetail } />

            <Route component={NotFound} />
        </Switch>

        <Footer />
    </div>
  </BrowserRouter>
`

Thanks

**Comment by bc-0dp** [comment]
looks like you got some typo's `packgae` !== `package`

**Comment by bc-0dp** [comment]
@becomevocal please close
