### ISSUE TITLE
Action App\Http\Controllers\MainController@error not defined.

### ISSUE THREAD

**Issue by Timothy2405** [bigcommerce/laravel-react-sample-app#11]
i follow every step but i got this mes in MainController , even when I clone the project in git back i still got the same mes
there is something wrong with 
return redirect()->action('MainController@error')->with('error_message', 'Not enough information was passed to install this app.');
please fixx this

**Comment by muscle-rhnkyr** [comment]
@BlueNotMe Just add 

` Route::get('error', 'MainController@error');`

on **routes/web.php**
